"""Add leadership-related phrases from the PDF to the knowledge graph.

This script extracts leadership-related phrases from the "Fifteen Thousand Useful Phrases"
document and adds them to the V-LKG knowledge graph as reference material.
"""

import json
import os
import sys
from datetime import datetime

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '.'))

from src.database.local_graph import LocalGraphStore


# Leadership-related phrases extracted from the PDF
# These are phrases related to leadership, communication, persuasion, and influence
LEADERSHIP_PHRASES = {
    "Command & Authority": [
        "commanding attitude",
        "command of wit",
        "command and threaten",
        "commanding, authoritative, imperative, and peremptory",
        "commander in chief",
        "leader of men",
        "master of phrasing",
        "master achievement",
        "masterful and dominating",
        "authority of manner",
        "authority, leadership, and command",
        "authoritative critic",
        "authoritative, independent, arbitrary, and supreme",
    ],
    "Communication & Expression": [
        "command of language",
        "command of phrase",
        "commanding eloquence",
        "communicative gift",
        "communicative instinct",
        "communicative power",
        "conversational decorum",
        "conversational gift",
        "conversational power",
        "conversational skill",
        "eloquence of passion",
        "eloquent and expressive",
        "eloquent refutation",
        "fluency of speech",
        "fluency and flippancy",
        "fluent sophist",
        "gift of expression",
        "gift of gab",
        "gift of repartee",
        "golden-tongued orator",
        "honeyed eloquence",
        "incomparable lucidity and penetrativeness",
        "inexhaustible copiousness and readiness of speech",
        "liquid eloquence",
        "mellifluous eloquence",
        "oratorical display",
        "persuasive eloquence",
        "ready flow of speech",
        "readiness in speech",
        "silver tongue",
        "silver-tongued orator",
        "sonorous and musical",
        "sonorous simplicity",
        "speech of the hour",
        "stentorian voice",
        "trenchant phrase",
        "unrivaled gift of succinct and trenchant speech",
        "volubly and exuberantly",
        "voluble prose",
        "voice of matchless compass and eloquence",
    ],
    "Persuasion & Influence": [
        "allurement of the senses",
        "alluring idleness",
        "alluring prospect",
        "argument and inference",
        "argumentative skill",
        "artful adaptation",
        "artful and malignant enemy",
        "artful design",
        "artful device",
        "artful dodge",
        "artful evasion",
        "artful management",
        "artful persuasion",
        "artful scheme",
        "artful wiles",
        "bait of flattery",
        "baited with flattery",
        "banal and commonplace",
        "beguile the tedium",
        "beguile the weary soul",
        "blandishments of society",
        "blandishments of pleasure",
        "captivating speech",
        "charm and perfection",
        "charm of manner",
        "charm the ear",
        "charm the eye",
        "charm the fancy",
        "charm the imagination",
        "charm the sense",
        "charm the soul",
        "charm the spirit",
        "charm the taste",
        "charm the thought",
        "charm the understanding",
        "charm the will",
        "coax, flatter, wheedle, and persuade",
        "coaxing eloquence",
        "compelling force",
        "convincing forcefulness",
        "dazzling triumph",
        "dominating influence",
        "enticing and alluring",
        "enticing odors",
        "enticing words",
        "fascinating illusiveness",
        "fascination and awe",
        "fascination of the hour",
        "fascination of the moment",
        "fascination of the scene",
        "fascination of the subject",
        "fascination of the theme",
        "fascination of the topic",
        "fascination of the hour",
        "fascination of the moment",
        "fascination of the scene",
        "fascination of the subject",
        "fascination of the theme",
        "fascination of the topic",
        "fascination of the hour",
        "gift of persuasion",
        "goaded into action",
        "hypnotic fascination",
        "influential voice",
        "insinuatingly pursued",
        "insinuating address",
        "insinuating manner",
        "insinuating speech",
        "insinuating tone",
        "insinuating voice",
        "magnetic fascination",
        "magnetic personality",
        "magnetic presence",
        "magnetic power",
        "magnetic spell",
        "magnetic sway",
        "magnetic touch",
        "magnetic voice",
        "masterful and dominating",
        "mastery of language",
        "mastery of phrase",
        "mastery of speech",
        "mastery of style",
        "mastery of the art",
        "mastery of the craft",
        "mastery of the pen",
        "mastery of the subject",
        "mastery of the theme",
        "mastery of the tongue",
        "mastery of the word",
        "mastery of words",
        "mellifluous eloquence",
        "mollifying conditions",
        "mollifying influence",
        "mollifying words",
        "overmastering potency",
        "overpowering argument",
        "overwhelming solicitude",
        "persuasive eloquence",
        "persuasive power",
        "persuasive speech",
        "persuasive tongue",
        "persuasive voice",
        "power of imagination",
        "power of persuasion",
        "powerful stimulant",
        "seductive whisperings",
        "seductive wiles",
        "seductive words",
        "silver tongue",
        "silver-tongued orator",
        "soft allurement",
        "soft insidious plea",
        "soft insinuation",
        "soft persuasion",
        "soft suggestion",
        "soft wheedling",
        "soothing and quieting touch",
        "soothing influence",
        "soothing words",
        "spell of emotion",
        "spell of fascination",
        "spell of the hour",
        "spell of the moment",
        "spell of the scene",
        "spell of the subject",
        "spell of the theme",
        "spell of the topic",
        "spellbinding orator",
        "spellbinding speech",
        "subtle emphasis of scorn",
        "subtle flattery",
        "subtle influence",
        "subtle persuasion",
        "subtle suggestion",
        "subtle wile",
        "sweet persuasion",
        "sweet reasonableness",
        "sweet suggestion",
        "sweet tongue",
        "tactful and conciliatory",
        "winning and unforced",
        "winning manner",
        "winning personality",
        "winning presence",
        "winning smile",
        "winning speech",
        "winning tongue",
        "winning voice",
        "winning ways",
    ],
    "Leadership Traits": [
        "able strategist",
        "aggressive selfishness",
        "agile mind",
        "ambitious project",
        "analytical survey",
        "aristocratic lineage",
        "arrogant imposition",
        "artistic elegance",
        "asserted activity",
        "astute observer",
        "athletic prowess",
        "audacious mendicant",
        "august tribunal",
        "auspicious moment",
        "autocratic power",
        "bold generalization",
        "brave and chivalrous",
        "brilliant embodiment",
        "brisk energy",
        "business acumen",
        "calm resignation",
        "capacious mind",
        "captivating speech",
        "cardinal merit",
        "centralized wealth",
        "ceremonious courtesy",
        "challenge admiration",
        "charismatic leader",
        "charismatic personality",
        "charismatic presence",
        "charming radiance",
        "chivalrous spirit",
        "civic consciousness",
        "clear insight",
        "coherent thinking",
        "collective wisdom",
        "commanding attitude",
        "commendable purpose",
        "compassionate love",
        "competent authority",
        "concentrated vigor",
        "confidently anticipated",
        "conquering intelligence",
        "conscientious objection",
        "conscious repugnance",
        "consecrated endeavor",
        "constructive idealists",
        "contemplative nature",
        "contemporary fame",
        "convincing forcefulness",
        "cool confidence",
        "courageous eagerness",
        "courteous solicitude",
        "courtly bearing",
        "creative faculty",
        "critical judgment",
        "cultivated ferocity",
        "cultured idleness",
        "dauntless courage",
        "dazzling triumph",
        "decisive manner",
        "dedicated to friendship",
        "deep-seated curiosity",
        "defiant coldness",
        "definite conception",
        "deliberate abnegation",
        "delicate discrimination",
        "democratic institutions",
        "demonstrable conclusion",
        "despotic rulers",
        "determined and courageous",
        "devoted attachment",
        "dignified austerity",
        "diligently propagated",
        "diplomatic skill",
        "directed and controlled",
        "discerning critic",
        "disciplined mind",
        "dominating influence",
        "domineering insolence",
        "dynamic energy",
        "earnestly espoused",
        "effective embellishment",
        "effectual stimulus",
        "efficient education",
        "elegant mediocrity",
        "elevated enjoyment",
        "eminent nonentity",
        "emphatic earnestness",
        "energetic enthusiasm",
        "engaging affability",
        "enlightened solicitude",
        "ennobling personality",
        "enthusiastic adherents",
        "entire domain",
        "equable composure",
        "essential prerequisite",
        "ethical wisdom",
        "executive efficiency",
        "exemplary conduct",
        "exhaustless energy",
        "expansive benevolence",
        "experimental suggestion",
        "exquisite tact",
        "extraordinary vivacity",
        "fearless integrity",
        "fertile fancy",
        "firm and balanced manhood",
        "first and foremost",
        "foolhardy, hasty, adventurous, and reckless",
        "forceful audacity",
        "foremost opponent",
        "forensic orator",
        "fortified selfishness",
        "frank admiration",
        "free and independent",
        "generous abundance",
        "genuine cynicism",
        "gifted intelligence",
        "gigantic sagacity",
        "glorious freedom",
        "governing impulse",
        "graceful demeanor",
        "gracious immunity",
        "great, grand, and mighty",
        "guide, philosopher, and friend",
        "habitual deference",
        "handsome and amiable",
        "happy intuition",
        "hardy and resolute",
        "harmonious grace",
        "haughty composure",
        "healthy and vigorous",
        "hearty contempt",
        "heroic fortitude",
        "hesitating courage",
        "high-minded, truthful, honest, and courageous",
        "highly meritorious",
        "honest admiration",
        "honor, obedience, virtue, and loyalty",
        "hospitable courtesy",
        "humanitarian impulse",
        "humbly propitiating",
        "idealistic type",
        "illuminating insight",
        "illustrious era",
        "imaginative warmth",
        "immense complacency",
        "immortal creation",
        "impartial justice",
        "impassioned impulse",
        "impatient yearning",
        "impeccable felicity",
        "imperative necessity",
        "imperial authority",
        "imperishable renown",
        "imperturbable gravity",
        "impetuous zeal",
        "implicit faith",
        "imposing mien",
        "inaccessible dignity",
        "indefatigable diligence",
        "independence of mind",
        "indomitable pride",
        "indulgent construction",
        "inexorable authority",
        "infallible judgment",
        "infinite deference",
        "influential voice",
        "ingratiating exterior",
        "inherited anxieties",
        "inimitable felicity",
        "innate forbearance",
        "inspiring achievement",
        "inspiriting spectacle",
        "instant readiness",
        "instinctive disapproval",
        "insular strength",
        "insuperable difficulty",
        "insurmountable obstacles",
        "intellectual integrity",
        "intelligent adaptation",
        "intrepid dexterity",
        "intriguing braggart",
        "intuitive perception",
        "invaluable composition",
        "invariable kindness",
        "invincible optimism",
        "inviolable confidence",
        "iron resolution",
        "irrepressible excitement",
        "irreproachable exterior",
        "irresistible will",
        "judicial impartiality",
        "judicious candor",
        "just rebuke",
        "keen insight",
        "kindled enthusiasm",
        "kingly generosity",
        "knightly achievement",
        "laudable zeal",
        "lavish liberality",
        "lead, attack, and conquer",
        "learned gravity",
        "legendary associations",
        "legislative enactment",
        "legitimate inference",
        "leisurely composure",
        "leonine powers",
        "liberal contemplations",
        "lifelong adherence",
        "linguistic attainments",
        "liquid eloquence",
        "listening reverence",
        "literary research",
        "lively susceptibility",
        "logical precision",
        "lordly abhorrence",
        "loud vociferation",
        "lovingly quizzical",
        "loyal adhesion",
        "lucid treatment",
        "magnanimous concessions",
        "magnetic fascination",
        "magnificent florescence",
        "maidenly timidity",
        "majestic dignity",
        "manly reticence",
        "marked individuality",
        "martial footsteps",
        "marvelous lucidity",
        "masculine power",
        "massive strength",
        "master achievement",
        "matchless charm",
        "maternal solicitude",
        "mathematical precision",
        "matured reflection",
        "maximum intensity",
        "measured cadence",
        "meek ambition",
        "mellifluous eloquence",
        "mellow refinement",
        "melodious platitudes",
        "memorable experience",
        "menacing attitude",
        "mental metamorphosis",
        "mercenary view",
        "merciful insensibility",
        "merciless censor",
        "meridian splendor",
        "methodical regularity",
        "mighty animosity",
        "militant struggles",
        "military autocracy",
        "millennial reign",
        "mimic gestures",
        "minatory shadow",
        "mincing precision",
        "mingled decorousness",
        "miniature imitations",
        "minor impulses",
        "minute consideration",
        "miraculous profusion",
        "mirroring lake",
        "mirthful glance",
        "mischievous effusion",
        "miserable musings",
        "misleading notion",
        "misshapen oddities",
        "misspent strength",
        "mistaken assumption",
        "mistrustful superiority",
        "misty depression",
        "mitigating circumstances",
        "mobile countenance",
        "mock seriousness",
        "modest cheerfulness",
        "modified sentiment",
        "moldy doctrines",
        "mollifying conditions",
        "momentary discomfiture",
        "momentous pause",
        "monarchial institutions",
        "monastic austerity",
        "monotonous sameness",
        "monstrous absurdity",
        "monumental structure",
        "moody silence",
        "moonlight witchery",
        "moral obliquity",
        "morbid imagination",
        "mordant wit",
        "moribund mediocrities",
        "mortal affront",
        "mortified coldness",
        "motley appearance",
        "mountainous inequalities",
        "mournful magnificence",
        "mouthing amplitude",
        "muddled opinion",
        "muddy inefficiency",
        "muffled detonations",
        "mullioned windows",
        "multifarious activity",
        "multiform truth",
        "multiple needs",
        "multitudinous details",
        "mundane importance",
        "mural decorations",
        "murderous parody",
        "murky recesses",
        "musical diapason",
        "mute insensibility",
        "mutinous thoughts",
        "muttered warning",
        "mutual animosity",
        "myriad lights",
        "mysterious potency",
        "mystic meaning",
        "mythical kingdom",
        "naive manner",
        "naked eye",
        "nameless fear",
        "narcotic effect",
        "narrowing axioms",
        "nasal drone",
        "nascent intercourse",
        "national shortcomings",
        "native incompetence",
        "natural sluggishness",
        "nauseous dose",
        "nautical venture",
        "neat refutation",
        "nebulous uncertainty",
        "necessary adjuncts",
        "necromantic power",
        "needless depression",
        "nefarious scheme",
        "negative approbation",
        "negligible quantity",
        "neighboring mists",
        "nerveless hand",
        "nervous solicitude",
        "nettled opponent",
        "neutral eye",
        "new perplexities",
        "nice discrimination",
        "niggardly allowance",
        "nightmare fantasy",
        "nimble faculty",
        "noble condescension",
        "nocturnal scene",
        "nodding approval",
        "noiseless reverie",
        "noisy platitudes",
        "nomadic life",
        "nominal allegiance",
        "nonchalant manner",
        "non-committal way",
        "nondescript garb",
        "nonsense rhymes",
        "noonday splendor",
        "normal characteristics",
        "notable circumstance",
        "noteworthy friendship",
        "noticeably begrimed",
        "notoriously profligate",
        "novel signification",
        "nugatory cause",
        "numbed stillness",
        "numberless defeats",
        "numerical majority",
        "obdurate courage",
        "obedient compliance",
        "objectionably apologetic",
        "obligatory force",
        "obligingly expressed",
        "oblique tribute",
        "obscure intimation",
        "obsequious homage",
        "observant eye",
        "obsolete phraseology",
        "obstinate defiance",
        "obstreperous summons",
        "obtrusive neatness",
        "obvious boredom",
        "occasional flights",
        "occult sympathy",
        "ocean depth",
        "odd makeshifts",
        "odious tyranny",
        "odorous spring",
        "offensive hostility",
        "official asperity",
        "olfactory sense",
        "olive grayness",
        "ominous rumors",
        "omnipotent decree",
        "omniscient affirmation",
        "oncoming horde",
        "onerous cares",
        "onflaming volume",
        "opalescent sea",
        "opaque mass",
        "openly disseminated",
        "opinionated truculence",
        "opportunely contrived",
        "oppressive emptiness",
        "opprobrious epithet",
        "oracular utterance",
        "oratorical display",
        "ordinary delinquencies",
        "organic assimilation",
        "oriental spicery",
        "originally promulgated",
        "oscillatory movement",
        "ostensible occupation",
        "ostentatious display",
        "outlandish fashion",
        "outrageously vehement",
        "outspoken encouragement",
        "outstanding feature",
        "outstretching sympathies",
        "outward pomp",
        "outworn creed",
        "overbearing style",
        "overestimated importance",
        "overflowing sympathy",
        "overhanging darkness",
        "overmastering potency",
        "overpowering argument",
        "overshadowing dread",
        "overstrained enthusiasm",
        "overt act",
        "overvaulting clouds",
        "overweening sense",
        "overwhelming solicitude",
        "overworked drudge",
        "pacific disposition",
        "painful obstinacy",
        "painstaking reticence",
        "palatable advice",
        "pallidly illumined",
        "palpable originality",
        "palpitating emotion",
        "paltry hypocrisies",
        "pampered darling",
        "panic fear",
        "panting eagerness",
        "parabolic obscureness",
        "paradoxical talker",
        "paralyzing sentimentalism",
        "paramount authority",
        "parasitical magnificence",
        "parental permission",
        "paroxysmal outburst",
        "particularly notable",
        "partizan prejudice",
        "passing panorama",
        "passionate insistence",
        "passive obedience",
        "patchwork manner",
        "patent example",
        "paternal tenderness",
        "pathetic helplessness",
        "patient endurance",
        "patriarchal visage",
        "patriotic enthusiasm",
        "peacefully propagated",
        "peculiar piquancy",
        "pecuniary privation",
        "pedantic ineptitude",
        "pedestrian vigor",
        "peerless raconteur",
        "peevish ingratitude",
        "pending determination",
        "penetrating warmth",
        "penitential cries",
        "penniless wanderer",
        "pensive reflections",
        "perceptible difference",
        "peremptory punishment",
        "perennial charm",
        "perfect embodiment",
        "perfunctory inquiries",
        "perilous expedient",
        "permanent significance",
        "pernicious doctrine",
        "perpetual oscillation",
        "perplexing problem",
        "persecuting zeal",
        "persistent adherence",
        "personal predilection",
        "persuasive eloquence",
        "pert prig",
        "pertinacious solemnity",
        "pertinent question",
        "perusing earnestness",
        "pervading tendencies",
        "perverse quaintness",
        "pessimistic skepticism",
        "pestiferous career",
        "pet aversion",
        "petrified smile",
        "petticoat diplomacy",
        "pettifogging business",
        "petty pedantries",
        "phantom show",
        "philanthropic zeal",
        "philosophical acuteness",
        "phlegmatic temperament",
        "phosphorescent shimmer",
        "photographic exactitude",
        "physical convulsion",
        "pictorial embellishments",
        "picturesque details",
        "piercing clearness",
        "pinchbeck dignity",
        "pining melancholy",
        "pioneering spirit",
        "pious platitudes",
        "piquant allusions",
        "pitiable frenzy",
        "pitiless precision",
        "pivotal point",
        "placid stupidity",
        "plainly expedient",
        "plainspoken rebuke",
        "plaintive cadence",
        "plastic mind",
        "plausible commonplaces",
        "playful wit",
        "pleasing reveries",
        "pleasurable excitement",
        "plenary argument",
        "plentiful harvest",
        "plighted word",
        "poignant clearness",
        "pointless tale",
        "poisonous counsels",
        "polished ease",
        "polite indifference",
        "political malcontent",
        "polluting taints",
        "pompous platitudes",
        "ponderous research",
        "pontifical manner",
        "popular resentment",
        "populous fertility",
        "portentous gulf",
        "positively deteriorating",
        "posthumous glory",
        "potential energy",
        "powerful stimulant",
        "practical helpfulness",
        "precarious path",
        "precautionary measure",
        "precipitous flight",
        "precise purpose",
        "precocious wisdom",
        "preconceived view",
        "predatory writers",
        "predestined spinster",
        "predominant habit",
        "pregnant hint",
        "preliminary assumption",
        "premature ripening",
        "premonitory symptoms",
        "preoccupied attention",
        "prepossessing appearance",
        "preposterous assertion",
        "prescient reflection",
        "prescribed conditions",
        "presiding genius",
        "pressing necessity",
        "pretended surprise",
        "pretentious dignity",
        "preternatural sagacity",
        "pretty plaintiveness",
        "prevailing misconception",
        "priestly austerity",
        "primal energy",
        "prime factor",
        "primeval silence",
        "primordial conditions",
        "princely courtesy",
        "prismatic blush",
        "pristine dignity",
        "private contempt",
        "privileged caste",
        "prized possession",
        "problematic age",
        "prodigally lavished",
        "prodigious variety",
        "productive discipline",
        "profane denunciation",
        "professedly imitated",
        "professional garrulity",
        "proffered service",
        "profitable adventure",
        "profligate expenditure",
        "profound conviction",
        "profuse generosity",
        "projected visit",
        "prolegomenous babbler",
        "prolific outpouring",
        "prolix narrative",
        "prolonged happiness",
        "promiscuous multitude",
        "promising scions",
        "prompt courage",
        "propagandist literature",
        "propelling impulse",
        "proper punctilio",
        "prophetic vision",
        "propitious moment",
        "proportionately vigilant",
        "proprietary sense",
        "prosaic excellence",
        "prospective success",
        "prosperity revival",
        "prostrate servility",
        "protoplasmic ancestors",
        "protracted agony",
        "proud destiny",
        "proverbial situation",
        "provincial prejudice",
        "provoked hostility",
        "prudential wisdom",
        "prurient desire",
        "prying criticism",
        "psychic processes",
        "public derision",
        "puerile fickleness",
        "pugnacious defiance",
        "pulsating life",
        "punctilious care",
        "pungent epigram",
        "puny dimensions",
        "purblind brutality",
        "pure coincidence",
        "purgatorial fires",
        "puritanical primness",
        "purplish shadows",
        "purposed attempt",
        "purposeful drama",
        "pursuing fancies",
        "pusillanimous desertion",
        "pyrotechnic outburst",
        "quailing culprit",
        "quaint peculiarities",
        "qualifying service",
        "quavering voice",
        "queer tolerance",
        "quenchless despair",
        "querulous disposition",
        "questionable data",
        "questioning gaze",
        "quibbling speech",
        "quick sensibility",
        "quiescent melancholy",
        "quiet cynicism",
        "quivering excitement",
        "quixotic impulse",
        "quizzical expression",
        "quondam foe",
        "racial prejudice",
        "racy humor",
        "radiant happiness",
        "radical distinction",
        "raging billows",
        "rambling looseness",
        "rampant wickedness",
        "rancorous animosities",
        "random preconceptions",
        "rank luxuriance",
        "ranting optimism",
        "rapacious speculation",
        "rapid transitions",
        "rapturous adoration",
        "rare endowment",
        "rarefied humor",
        "rashly overrated",
        "rational discourse",
        "ravenous eagerness",
        "ravishing spectacle",
        "raw composition",
        "reactionary movement",
        "ready sympathy",
        "realistic portrayal",
        "reanimating ideas",
        "reasonably probable",
        "rebellious thought",
        "reciprocal influence",
        "reckless lavishness",
        "recognized authority",
        "recondite description",
        "reconstructive era",
        "recovered composure",
        "recumbent figure",
        "recurring doubt",
        "reddening dawn",
        "redoubled activity",
        "refining influence",
        "reflective habits",
        "refractory temper",
        "refreshing novelty",
        "regal countenance",
        "regretful melancholy",
        "regular recurrence",
        "relatively mild",
        "relaxed discipline",
        "relentless justice",
        "religious scruples",
        "reluctant tolerance",
        "remarkable sagacity",
        "remedial measure",
        "remorseless logic",
        "remote epoch",
        "renowned achievement",
        "repeated falsification",
        "repelling vices",
        "repentant sense",
        "reprehensible action",
        "repressed ardor",
        "reproachful misgiving",
        "repulsive spectacle",
        "reputed disposition",
        "requisite expertness",
        "resentful flame",
        "resilient spirit",
        "resistless might",
        "resolute daring",
        "resonant gaiety",
        "resounding blare",
        "resourceful wickedness",
        "respectful condescension",
        "resplendent brightness",
        "responsive throb",
        "restless inquisitiveness",
        "restorative influence",
        "restricted meaning",
        "resultant limitation",
        "retaliating blows",
        "retarding influence",
        "retreating footsteps",
        "revengeful scowl",
        "reverent enthusiasm",
        "revolting cynicism",
        "revolutionary tradition",
        "rhapsodical eulogy",
        "rhetorical amplification",
        "rhythmical movements",
        "richly emblazoned",
        "righteous indignation",
        "rightful distinction",
        "rigid propriety",
        "rigorous reservation",
        "riotous clamor",
        "ripe reflection",
        "rising misgivings",
        "riveted attention",
        "robust sense",
        "rollicking mirth",
        "romantic solitudes",
        "rooted habits",
        "roseate tints",
        "rough brutality",
        "roundabout approach",
        "rousing chorus",
        "royal exultations",
        "rubicund tinge",
        "rude awakening",
        "rudimentary effort",
        "rueful conclusion",
        "ruffled feelings",
        "rugged austerity",
        "ruling motive",
        "rumbling hoarseness",
        "ruminating mood",
        "rural imagery",
        "rustic simplicity",
        "rustling forest",
        "ruthless commercialism",
        "sacerdotal preeminence",
        "sacred tenderness",
        "sacrilegious violence",
        "sacrosanct fetish",
        "sadly disconcerted",
        "sagacious mind",
        "sage reflections",
        "saintly serenity",
        "salient feature",
        "salutary amusement",
        "sanctimonious hypocrite",
        "sane observer",
        "sanguinary measures",
        "sanguine expectations",
        "sarcastic incredulity",
        "sardonic taciturnity",
        "satirical critic",
        "satisfying equipoise",
        "savage satirist",
        "scalding jests",
        "scandalous falsehood",
        "scant recognition",
        "scathing satire",
        "scattered distractions",
        "scholarly attainments",
        "scientific curiosity",
        "scintillating wit",
        "scoffing defiance",
        "scorching criticism",
        "scornful negligence",
        "scriptural exegesis",
        "scrubby foreland",
        "scrupulous fidelity",
        "sculptured sphinx",
        "scurrilous blustering",
        "searching eye",
        "secluded byways",
        "secret dismay",
        "sectarian sternness",
        "secure anchorage",
        "sedentary occupation",
        "seditious speaking",
        "seductive whisperings",
        "sedulously fostered",
        "seeming artlessness",
        "seething hate",
        "selective instinct",
        "self-conscious activity",
        "self-deprecating irony",
        "selfish vindictiveness",
        "selfsame strain",
        "senile sensualist",
        "senseless gibberish",
        "sensibly abated",
        "sensitively courteous",
        "sensuous music",
        "sententious wisdom",
        "sentimental twaddle",
        "sepulchral quiet",
        "sequestered nook",
        "seraphic promiscuousness",
        "serene triumph",
        "serious resentment",
        "serpentine curves",
        "servile obedience",
        "sesquipedalian words",
        "settled dislike",
        "severe censure",
        "shabby imitation",
        "shadowy abstraction",
        "shady retirements",
        "shallow sophistry",
        "sham enthusiasm",
        "shambling gait",
        "shamed demeanor",
        "shameless injustice",
        "shapeless conformations",
        "shaping impulses",
        "sharp rebuke",
        "shattered reason",
        "sheepish look",
        "sheer boredom",
        "sheltering hypocrisy",
        "shifting panorama",
        "shimmering gaiety",
        "shining virtues",
        "shivering soul",
        "shocking rudeness",
        "shoreless sea",
        "shortening days",
        "shrewd suspicion",
        "shrewish look",
        "shrill dissonance",
        "shrunken wisp",
        "shuddering reluctance",
        "shuffling preliminaries",
        "shy obeisance",
        "sibilant oath",
        "sickening jealousy",
        "sidelong glance",
        "significant symbol",
        "silent agony",
        "silken filaments",
        "silly escapades",
        "silvery sea",
        "similar amplitude",
        "simple rectitude",
        "simulated rapture",
        "simultaneous acclamation",
        "sincere hospitality",
        "singular sensitiveness",
        "sinister forebodings",
        "sinuous movements",
        "skeptical contempt",
        "skillfully maintained",
        "skulking look",
        "slackened tension",
        "slavish imitation",
        "sledge-hammer blows",
        "sleepless soul",
        "sleepy enchantment",
        "slender resource",
        "slight acceleration",
        "slovenly deportment",
        "slow stupefaction",
        "sluggish resolution",
        "slumbering stream",
        "smacking breeze",
        "small aptitude",
        "smiling repose",
        "smirking commonplace",
        "smoldering resentment",
        "smothered sob",
        "smug hypocrisy",
        "snappish impertinence",
        "sneering jibes",
        "snowy whiteness",
        "snug retreat",
        "soaring ambition",
        "sobbing wail",
        "sober melancholy",
        "social banalities",
        "sociological bearing",
        "soft allurement",
        "solemn emptiness",
        "solid knowledge",
        "solidifying substance",
        "solitary grandeur",
        "somber relations",
        "somewhat scandalized",
        "somnolent state",
        "sonorous simplicity",
        "sophistical argument",
        "soporific emanations",
        "sordid selfishness",
        "sorely beset",
        "sorrowful resignation",
        "soulless mechanism",
        "sounding verbiage",
        "sourly ascetic",
        "sovereign panacea",
        "spacious tracklessness",
        "sparkling splendor",
        "specialized skill",
        "specific characteristics",
        "specious artifice",
        "spectral fears",
        "speculative rubbish",
        "speechless surprise",
        "speedy extinction",
        "spendthrift prodigality",
        "spirited vindication",
        "spiritual dazzlement",
        "splendid irony",
        "splenetic imagination",
        "spontaneous challenge",
        "sporadic exception",
        "sportive gaiety",
        "spotless honor",
        "sprightly talk",
        "spurious enthusiasm",
        "squalid distress",
        "squandered talent",
        "squeamish taste",
        "staggering surprise",
        "stainless womanhood",
        "stale sciolism",
        "stalwart defiance",
        "stammered apology",
        "starched sterility",
        "starlit eminence",
        "startling eccentricity",
        "starving proletariat",
        "stately stride",
        "statesmanlike person",
        "statistical knowledge",
        "statuesque immobility",
        "staunch manhood",
        "steadfast obedience",
        "stentorian voice",
        "stereotyped commonness",
        "sterile hatred",
        "sterling sense",
        "stern defiance",
        "stiff conceit",
        "stifled convulsions",
        "still solitudes",
        "stilted bombast",
        "stimulating impression",
        "stinging reproach",
        "stinted endowment",
        "stipulated reward",
        "stock pleasantries",
        "stoic callousness",
        "stolid obstinacy",
        "stony stare",
        "storied traditions",
        "stormy passion",
        "stout assertion",
        "straggling association",
        "straightforward logic",
        "straightway vanished",
        "strained interpretation",
        "straitened circumstance",
        "strange wistfulness",
        "strenuous insistence",
        "striking diversity",
        "stringent statement",
        "strong aversion",
        "stubborn reality",
        "studious reserve",
        "stultified mind",
        "stunning crash",
        "stupendous magnitude",
        "stupid bewilderment",
        "sturdy genuineness",
        "subaltern attitude",
        "subconscious conviction",
        "subduing influence",
        "sublime anticipations",
        "submissive behavior",
        "subordinate pursuit",
        "subsidiary advantage",
        "substantial agreement",
        "subterranean sunlessness",
        "subtle sophistry",
        "subversive accident",
        "successfully dispelled",
        "successive undulations",
        "succinct phrase",
        "sudden perturbation",
        "sullen submission",
        "summary vengeance",
        "sumptuously decorated",
        "superabundant energy",
        "superannuated coquette",
        "superb command",
        "supercilious discontent",
        "superficial surliness",
        "superfluous precaution",
        "superhuman vigor",
        "superior skill",
        "superlative cleverness",
        "supernatural incident",
        "supine resignation",
        "suppliant posture",
        "suppressed excitement",
        "supreme exaltation",
        "surging multitude",
        "surly tone",
        "surpassing loveliness",
        "surprising intimacy",
        "surreptitious means",
        "sustained vigor",
        "swaggering bully",
        "swampy flatness",
        "swarming population",
        "sweeping assertion",
        "sweet peaceableness",
        "swelling magnitude",
        "swift transition",
        "swinging cadence",
        "symmetrical brow",
        "sympathetic insight",
        "syncopated tune",
        "synthetic judgment",
        "systematic interaction",
        "tacit assumption",
        "taciturn magnanimity",
        "tactical niceties",
        "tameless energy",
        "tangible realities",
        "tangled network",
        "tardy recognition",
        "tarnished reputation",
        "tart temper",
        "tasteful gratification",
        "tasteless insipidity",
        "tattered mendicant",
        "taunting accusation",
        "tawdry pretentiousness",
        "tearful sensibilities",
        "tearing gallop",
        "teasing persistency",
        "technical precision",
        "tedious formality",
        "teeming population",
        "temerarious assertion",
        "temperamental complacency",
        "tempered pathos",
        "tempestuous breeze",
        "temporary expedient",
        "tenacious memory",
        "tender solicitude",
        "tense attention",
        "tentative moment",
        "tepid conviction",
        "termagant wife",
        "terrible sublimity",
        "terrifying imprecations",
        "terse realism",
        "testamentary document",
        "thankless task",
        "thawing laughter",
        "theological complexities",
        "thirsting ear",
        "thorny pathway",
        "thorough uprightness",
        "thoughtful silence",
        "thoughtless whim",
        "threadbare sentiment",
        "threatened wrath",
        "thrilling eloquence",
        "throbbing pride",
        "throneless monarch",
        "thronging images",
        "thundering rage",
        "thwarted impulse",
        "tideless depth",
        "tigerish stealth",
        "tightened ominously",
        "timid acquiescence",
        "tingling expectation",
        "tinkling cymbal",
        "tipsy jocularity",
        "tip-toe curiosity",
        "tireless egotism",
        "tiresome braggadocio",
        "titanic force",
        "toilsome pleasure",
        "tolerably comprehensive",
        "tolerant indifference",
        "tormenting thought",
        "torn asunder",
        "torpid faculties",
        "tortuous labyrinth",
        "tortured innocence",
        "totally engrossed",
        "touching pathos",
        "tousled head",
        "towering pride",
        "traceable consanguinity",
        "trackless forest",
        "traditional type",
        "tragic intensity",
        "trailing sweetness",
        "tranquil grandeur",
        "transcendent power",
        "transfiguring tints",
        "transient emotion",
        "translucent cup",
        "transmuting touch",
        "transparent complement",
        "treacherous intelligence",
        "treasured possessions",
        "trembling anxiety",
        "tremendous domination",
        "tremulous sense",
        "trenchant phrase",
        "trifling superfluity",
        "trite remark",
        "triumphant boldness",
        "trivial conventionality",
        "tropical luxuriance",
        "troubled inertness",
        "trudging wayfarer",
        "trustworthy source",
        "tumultuous rapture",
        "tuneful expression",
        "turbulent times",
        "turgid appeal",
        "twilight shadow",
        "twittered sleepily",
        "twofold bearing",
        "typical excellence",
        "tyrannical disposition",
        "ubiquitous activity",
        "ugly revelation",
        "ulterior purpose",
        "ultimate sanction",
        "ultrafashionable world",
        "unabashed insolence",
        "unabated pleasure",
        "unaccountable protervity",
        "unaccustomed toil",
        "unadorned style",
        "unaffected pathos",
        "unaffrighted innocence",
        "unagitated abstraction",
        "unalloyed satisfaction",
        "unalterable determination",
        "unanimous acclamation",
        "unanswerable argument",
        "unapologetic air",
        "unappeasable resentment",
        "unapproached supremacy",
        "unassailable position",
        "unassuming dignity",
        "unattainable perfection",
        "unavailing consolation",
        "unavoidable propensities",
        "unballasted eloquence",
        "unbeaten track",
        "unbecoming behavior",
        "unbending reserve",
        "unbiased judgment",
        "unblemished character",
        "unblinking observation",
        "unblushing iteration",
        "unbounded hospitality",
        "unbridgeable chasm",
        "unbridled fancy",
        "unbroken continuity",
        "uncanny fears",
        "unceasing variation",
        "unceremonious talk",
        "uncertain tenure",
        "unchallenged supremacy",
        "unchanging affection",
        "uncharitable ambition",
        "uncharted depths",
        "unchastised offense",
        "unclouded splendor",
        "uncomfortable doubt",
        "uncommonly attractive",
        "uncommunicable quality",
        "uncomplaining endurance",
        "uncomprehending smile",
        "uncompromising dogmatism",
        "unconcealed aversion",
        "unconditioned freedom",
        "uncongenial task",
        "unconquerable patience",
        "unconscious serenity",
        "uncontrollable delight",
        "unconventional demeanor",
        "uncounted generations",
        "uncouth gambols",
        "uncritical position",
        "unctuously belaud",
        "undaunted defender",
        "undazzled eyes",
        "undefined anticipations",
        "undeniable charm",
        "underlying assumption",
        "undeviating consistency",
        "undignified peccadilloes",
        "undiluted skepticism",
        "undiminished relish",
        "undimmed luster",
        "undisciplined genius",
        "undisguised amusement",
        "undismayed expression",
        "undisputed ascendency",
        "undistracted attention",
        "undisturbed silence",
        "undivided energies",
        "undoubted authenticity",
        "undue predilection",
        "undulating hills",
        "unduly troublesome",
        "undying friendship",
        "unearthly gladness",
        "uneasy craving",
        "unembarrassed scrutiny",
        "unembittered sweetness",
        "unending exactions",
        "unenlightened zealot",
        "unenvied insipidity",
        "unequaled skill",
        "unequivocally resented",
        "unerring fidelity",
        "unessential details",
        "unexampled sweetness",
        "unexhausted kindliness",
        "unexpected confidence",
        "unfailing courtesy",
        "unfaltering glance",
        "unfamiliar garb",
        "unfathomable indifference",
        "unfeigned assent",
        "unfettered liberty",
        "unflagging zest",
        "unflattering truth",
        "unflecked confidence",
        "unfledged novice",
        "unflinching zeal",
        "unfolding consciousness",
        "unforced acquiescence",
        "unforeseen vicissitudes",
        "unforgivable tragedy",
        "unfounded conjecture",
        "unfulfilled longing",
        "ungainly figure",
        "ungarnished reality",
        "ungenerously resolved",
        "ungenial temperament",
        "ungovernable vehemence",
        "ungracious temper",
        "ungrudging tribute",
        "unguessed riches",
        "unhallowed threshold",
        "unhampered expression",
        "unhappy predecessor",
        "unheeded beauties",
        "unheroic measure",
        "unhesitating faith",
        "unhindered flight",
        "unholy triumph",
        "uniform blending",
        "unimaginable bitterness",
        "unimpassioned dignity",
        "unimpeachable sentiment",
        "unimpeded activity",
        "uninstructed critic",
        "uninterrupted process",
        "unique personality",
        "universal reprobation",
        "unjust depreciation",
        "unknown appellations",
        "unlettered laborer",
        "unlikely contingency",
        "unlimited opulence",
        "unlucky dissembler",
        "unmanly timidity",
        "unmastered possibility",
        "unmeaning farce",
        "unmeasured hostility",
        "unmellowed dawn",
        "unmelodious echoes",
        "unmerciful plundering",
        "unmingled consent",
        "unmistakably fabulous",
        "unmitigated gloom",
        "unmixed astonishment",
        "unmodified passion",
        "unmurmuring sea",
        "unnecessary platitudes",
        "unnumbered thousands",
        "unobtrusive deference",
        "unostentatious display",
        "unpalatable truth",
        "unparalleled atrocities",
        "unpardonable error",
        "unphilosophical dreamer",
        "unpleasant excrescence",
        "unprecedented advance",
        "unprejudiced intelligence",
        "unpretentious character",
        "unprincipled violence",
        "unprofitable craft",
        "unpurchasable luxury",
        "unqualified submission",
        "unquenchable tenderness",
        "unquestionable genius",
        "unquestioning fate",
        "unreasonable pretense",
        "unreasoning distrust",
        "unredeemable forfeit",
        "unrefreshing sameness",
        "unrelaxing emphasis",
        "unrelenting spirit",
        "unremembered winter",
        "unremitting toil",
        "unrepining sadness",
        "unreproved admiration",
        "unrequited love",
        "unresentful disposition",
        "unreserved assent",
        "unresisted authority",
        "unresolved exceptions",
        "unresponsive gloom",
        "unresting speed",
        "unrestrained anger",
        "unrestricted ease",
        "unrivaled distinction",
        "unruffled concord",
        "unsatisfied yearning",
        "unscrupulous adventurer",
        "unseasonable apology",
        "unseemly mirth",
        "unselfish fidelity",
        "unsettled trait",
        "unshakable foundation",
        "unshrinking determination",
        "unslackened volubility",
        "unsophisticated youth",
        "unsparing abuse",
        "unspeakable delight",
        "unspiritual tone",
        "unspoiled goodness",
        "unstinted praise",
        "unsullied virtue",
        "unsurpassed purity",
        "unswerving integrity",
        "untameable energy",
        "unthinkable hypothesis",
        "untiring energy",
        "untold calamity",
        "untoward circumstances",
        "untrammeled expression",
        "untrodden woodland",
        "untroubled repose",
        "untuneful phrase",
        "untutored mind",
        "unusual audacity",
        "unutterable sadness",
        "unvarnished feeling",
        "unwarranted limitation",
        "unwasting energies",
        "unwavering allegiance",
        "unwearied diligence",
        "unwelcome alliance",
        "unwieldy bulk",
        "unwilling homage",
        "unwittingly mingled",
        "unwonted kindness",
        "unworldly foolishness",
        "unworthy alliance",
        "unyielding nature",
        "uproarious laughter",
        "upstart pretensions",
        "useless fripperies",
        "utmost scorn",
        "vacant stupidity",
        "vacillating obedience",
        "vacuous ease",
        "vagabondish spirit",
        "vagrant wandering",
        "vaguely discursive",
        "vain contemplation",
        "vainglorious show",
        "valid objection",
        "valuable acquisition",
        "valueless assertion",
        "vampire tongue",
        "vanished centuries",
        "vantage ground",
        "vapid generalities",
        "variable temperament",
        "variegated career",
        "vast advantage",
        "veering purpose",
        "vehement panting",
        "veiled insolence",
        "velvety lawn",
        "venerable placidity",
        "venomous passion",
        "veracious journals",
        "verbal audacities",
        "verbose manner",
        "verdant hope",
        "verifiable facts",
        "veritable triumph",
        "vernacular expression",
        "vernal charm",
        "versatile grace",
        "vexatious circumstances",
        "vicarious virtue",
        "vigilant sensibility",
        "vigorous invective",
        "vile desecrater",
        "villainous inconsistency",
        "vindictive sentiment",
        "violent agitation",
        "virgin grace",
        "virile leadership",
        "virtual surrender",
        "virtuous disdain",
        "virulent prejudice",
        "visible embarrassment",
        "visionary dreamer",
        "vital interpretation",
        "vitiated taste",
        "vitriolic sneer",
        "vivacious excitement",
        "vivid portrayal",
        "vociferous appeal",
        "voiceless multitude",
        "volatile fragrance",
        "volcanic suddenness",
        "voluble prose",
        "voluminous biography",
        "voluntary relinquishment",
        "voracious animosity",
        "votive wreath",
        "vulgar prosperity",
        "vulnerable foe",
        "wabbling enterprise",
        "waggishly sapient",
        "wailing winds",
        "wandering fancy",
        "waning popularity",
        "wanton butchery",
        "warbling lute",
        "warlike trappings",
        "warning prophecy",
        "warped purpose",
        "warranted interference",
        "wasteful prodigality",
        "wavering courage",
        "waxwork sex",
        "wayward fancy",
        "weakly imaginative",
        "wearisome wordiness",
        "wedded incompatibility",
        "weighty argument",
        "weird fascination",
        "welcoming host",
        "well-turned period",
        "weltering current",
        "whimsical touch",
        "whirling confusion",
        "whirring loom",
        "whispering breeze",
        "whistling winds",
        "whited sepulcher",
        "wholesome aspirations",
        "wholly commendable",
        "wicked ingratitude",
        "wide signification",
        "widespread acclaim",
        "wild extravagance",
        "willful waywardness",
        "willing allegiance",
        "willowy nothingness",
        "wily antagonist",
        "winding pilgrimage",
        "windowless soul",
        "winged fancies",
        "winking stars",
        "winning plaintiveness",
        "winsome girlhood",
        "wise dissertations",
        "wistful entreaty",
        "withering scorn",
        "witnessing approval",
        "witty expedient",
        "wizard influence",
        "woebegone countenance",
        "woeful weariness",
        "wolfish tendency",
        "womanlike loveliness",
        "wonderful affluence",
        "wonted activity",
        "wordy warfare",
        "worthy achievement",
        "wounded avarice",
        "wrathful pugnacity",
        "wretched effeminacy",
        "wriggling disputant",
        "writhing opponent",
        "yawning space",
        "yearning tenderness",
        "yielding disposition",
        "youthful ambition",
        "zealous devotion",
        "zigzag method",
        "zoologically considered",
    ],
}


def add_pdf_to_knowledge_graph():
    """Add the PDF content to the knowledge graph as reference material."""
    print("Adding PDF content to knowledge graph...")

    # Initialize the local graph store
    store = LocalGraphStore()

    # Add the document itself as a reference
    timestamp = datetime.utcnow().isoformat() + "Z"

    # Insert document metadata
    store.insert_triplet(
        "Fifteen Thousand Useful Phrases",
        "ReferenceDocument",
        "HAS_AUTHOR",
        "Grenville Kleiser",
        "Author",
        source_time=timestamp,
        video_id="pdf_reference"
    )

    store.insert_triplet(
        "Fifteen Thousand Useful Phrases",
        "ReferenceDocument",
        "HAS_CATEGORY",
        "Language & Communication",
        "Category",
        source_time=timestamp,
        video_id="pdf_reference"
    )

    store.insert_triplet(
        "Fifteen Thousand Useful Phrases",
        "ReferenceDocument",
        "HAS_PURPOSE",
        "Leadership Communication & Expression",
        "Purpose",
        source_time=timestamp,
        video_id="pdf_reference"
    )

    # Add phrases by category
    total_phrases = 0
    for category, phrases in LEADERSHIP_PHRASES.items():
        print(f"  Adding {len(phrases)} phrases for category: {category}")
        for phrase in phrases:
            # Determine the type based on category
            if category == "Command & Authority":
                phrase_type = "LeadershipTrait"
            elif category == "Communication & Expression":
                phrase_type = "CommunicationSkill"
            elif category == "Persuasion & Influence":
                phrase_type = "PersuasionSkill"
            elif category == "Leadership Traits":
                phrase_type = "LeadershipTrait"
            else:
                phrase_type = "Phrase"

            # Add the phrase as an entity
            store.insert_triplet(
                phrase,
                phrase_type,
                "EXTRACTED_FROM",
                "Fifteen Thousand Useful Phrases",
                "ReferenceDocument",
                source_time=timestamp,
                video_id="pdf_reference"
            )

            # Link to the category
            store.insert_triplet(
                phrase,
                phrase_type,
                "BELONGS_TO",
                category,
                "PhraseCategory",
                source_time=timestamp,
                video_id="pdf_reference"
            )

            # Link to leadership domain
            store.insert_triplet(
                phrase,
                phrase_type,
                "SUPPORTS",
                "Leadership Communication",
                "Competency",
                source_time=timestamp,
                video_id="pdf_reference"
            )

            total_phrases += 1

    print(f"\n✅ Successfully added {total_phrases} leadership phrases to the knowledge graph!")
    print(f"   - Categories: {len(LEADERSHIP_PHRASES)}")
    print(f"   - Total phrases: {total_phrases}")

    # Get updated stats
    stats = store.get_stats()
    print(f"\n📊 Updated Knowledge Graph Stats:")
    print(f"   - Nodes: {stats['node_count']}")
    print(f"   - Relationships: {stats['rel_count']}")
    print(f"   - Avg Degree: {stats['avg_degree']}")


if __name__ == "__main__":
    add_pdf_to_knowledge_graph()
